# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/hkumar/clion-2020.2/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/hkumar/clion-2020.2/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hkumar/cross_library_execution

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hkumar/cross_library_execution

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/hkumar/clion-2020.2/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/hkumar/clion-2020.2/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hkumar/cross_library_execution/CMakeFiles /home/hkumar/cross_library_execution/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hkumar/cross_library_execution/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cross_library_execution

# Build rule for target.
cross_library_execution: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cross_library_execution
.PHONY : cross_library_execution

# fast build rule for target.
cross_library_execution/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library_execution.dir/build.make CMakeFiles/cross_library_execution.dir/build
.PHONY : cross_library_execution/fast

#=============================================================================
# Target rules for targets named cross_library

# Build rule for target.
cross_library: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cross_library
.PHONY : cross_library

# fast build rule for target.
cross_library/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/build
.PHONY : cross_library/fast

ArrayFireOperations/ArrayFireAdapter.o: ArrayFireOperations/ArrayFireAdapter.cu.o

.PHONY : ArrayFireOperations/ArrayFireAdapter.o

# target to build an object file
ArrayFireOperations/ArrayFireAdapter.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/ArrayFireOperations/ArrayFireAdapter.cu.o
.PHONY : ArrayFireOperations/ArrayFireAdapter.cu.o

ArrayFireOperations/ArrayFireAdapter.i: ArrayFireOperations/ArrayFireAdapter.cu.i

.PHONY : ArrayFireOperations/ArrayFireAdapter.i

# target to preprocess a source file
ArrayFireOperations/ArrayFireAdapter.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/ArrayFireOperations/ArrayFireAdapter.cu.i
.PHONY : ArrayFireOperations/ArrayFireAdapter.cu.i

ArrayFireOperations/ArrayFireAdapter.s: ArrayFireOperations/ArrayFireAdapter.cu.s

.PHONY : ArrayFireOperations/ArrayFireAdapter.s

# target to generate assembly for a file
ArrayFireOperations/ArrayFireAdapter.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/ArrayFireOperations/ArrayFireAdapter.cu.s
.PHONY : ArrayFireOperations/ArrayFireAdapter.cu.s

ArrayFireOperations/afComputeOps.o: ArrayFireOperations/afComputeOps.cu.o

.PHONY : ArrayFireOperations/afComputeOps.o

# target to build an object file
ArrayFireOperations/afComputeOps.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/ArrayFireOperations/afComputeOps.cu.o
.PHONY : ArrayFireOperations/afComputeOps.cu.o

ArrayFireOperations/afComputeOps.i: ArrayFireOperations/afComputeOps.cu.i

.PHONY : ArrayFireOperations/afComputeOps.i

# target to preprocess a source file
ArrayFireOperations/afComputeOps.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/ArrayFireOperations/afComputeOps.cu.i
.PHONY : ArrayFireOperations/afComputeOps.cu.i

ArrayFireOperations/afComputeOps.s: ArrayFireOperations/afComputeOps.cu.s

.PHONY : ArrayFireOperations/afComputeOps.s

# target to generate assembly for a file
ArrayFireOperations/afComputeOps.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/ArrayFireOperations/afComputeOps.cu.s
.PHONY : ArrayFireOperations/afComputeOps.cu.s

Base/BaseCompute.o: Base/BaseCompute.cpp.o

.PHONY : Base/BaseCompute.o

# target to build an object file
Base/BaseCompute.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/Base/BaseCompute.cpp.o
.PHONY : Base/BaseCompute.cpp.o

Base/BaseCompute.i: Base/BaseCompute.cpp.i

.PHONY : Base/BaseCompute.i

# target to preprocess a source file
Base/BaseCompute.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/Base/BaseCompute.cpp.i
.PHONY : Base/BaseCompute.cpp.i

Base/BaseCompute.s: Base/BaseCompute.cpp.s

.PHONY : Base/BaseCompute.s

# target to generate assembly for a file
Base/BaseCompute.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/Base/BaseCompute.cpp.s
.PHONY : Base/BaseCompute.cpp.s

BoostOperations/BoostAdapter.o: BoostOperations/BoostAdapter.cpp.o

.PHONY : BoostOperations/BoostAdapter.o

# target to build an object file
BoostOperations/BoostAdapter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/BoostOperations/BoostAdapter.cpp.o
.PHONY : BoostOperations/BoostAdapter.cpp.o

BoostOperations/BoostAdapter.i: BoostOperations/BoostAdapter.cpp.i

.PHONY : BoostOperations/BoostAdapter.i

# target to preprocess a source file
BoostOperations/BoostAdapter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/BoostOperations/BoostAdapter.cpp.i
.PHONY : BoostOperations/BoostAdapter.cpp.i

BoostOperations/BoostAdapter.s: BoostOperations/BoostAdapter.cpp.s

.PHONY : BoostOperations/BoostAdapter.s

# target to generate assembly for a file
BoostOperations/BoostAdapter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/BoostOperations/BoostAdapter.cpp.s
.PHONY : BoostOperations/BoostAdapter.cpp.s

BoostOperations/BoostComputeOps.o: BoostOperations/BoostComputeOps.cpp.o

.PHONY : BoostOperations/BoostComputeOps.o

# target to build an object file
BoostOperations/BoostComputeOps.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/BoostOperations/BoostComputeOps.cpp.o
.PHONY : BoostOperations/BoostComputeOps.cpp.o

BoostOperations/BoostComputeOps.i: BoostOperations/BoostComputeOps.cpp.i

.PHONY : BoostOperations/BoostComputeOps.i

# target to preprocess a source file
BoostOperations/BoostComputeOps.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/BoostOperations/BoostComputeOps.cpp.i
.PHONY : BoostOperations/BoostComputeOps.cpp.i

BoostOperations/BoostComputeOps.s: BoostOperations/BoostComputeOps.cpp.s

.PHONY : BoostOperations/BoostComputeOps.s

# target to generate assembly for a file
BoostOperations/BoostComputeOps.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/BoostOperations/BoostComputeOps.cpp.s
.PHONY : BoostOperations/BoostComputeOps.cpp.s

ThrustOperations/ThrustAdapter.o: ThrustOperations/ThrustAdapter.cu.o

.PHONY : ThrustOperations/ThrustAdapter.o

# target to build an object file
ThrustOperations/ThrustAdapter.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/ThrustOperations/ThrustAdapter.cu.o
.PHONY : ThrustOperations/ThrustAdapter.cu.o

ThrustOperations/ThrustAdapter.i: ThrustOperations/ThrustAdapter.cu.i

.PHONY : ThrustOperations/ThrustAdapter.i

# target to preprocess a source file
ThrustOperations/ThrustAdapter.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/ThrustOperations/ThrustAdapter.cu.i
.PHONY : ThrustOperations/ThrustAdapter.cu.i

ThrustOperations/ThrustAdapter.s: ThrustOperations/ThrustAdapter.cu.s

.PHONY : ThrustOperations/ThrustAdapter.s

# target to generate assembly for a file
ThrustOperations/ThrustAdapter.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/ThrustOperations/ThrustAdapter.cu.s
.PHONY : ThrustOperations/ThrustAdapter.cu.s

ThrustOperations/ThrustComputeOps.o: ThrustOperations/ThrustComputeOps.cu.o

.PHONY : ThrustOperations/ThrustComputeOps.o

# target to build an object file
ThrustOperations/ThrustComputeOps.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/ThrustOperations/ThrustComputeOps.cu.o
.PHONY : ThrustOperations/ThrustComputeOps.cu.o

ThrustOperations/ThrustComputeOps.i: ThrustOperations/ThrustComputeOps.cu.i

.PHONY : ThrustOperations/ThrustComputeOps.i

# target to preprocess a source file
ThrustOperations/ThrustComputeOps.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/ThrustOperations/ThrustComputeOps.cu.i
.PHONY : ThrustOperations/ThrustComputeOps.cu.i

ThrustOperations/ThrustComputeOps.s: ThrustOperations/ThrustComputeOps.cu.s

.PHONY : ThrustOperations/ThrustComputeOps.s

# target to generate assembly for a file
ThrustOperations/ThrustComputeOps.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/ThrustOperations/ThrustComputeOps.cu.s
.PHONY : ThrustOperations/ThrustComputeOps.cu.s

cudfOperations/cudfComputeOps.o: cudfOperations/cudfComputeOps.cu.o

.PHONY : cudfOperations/cudfComputeOps.o

# target to build an object file
cudfOperations/cudfComputeOps.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/cudfOperations/cudfComputeOps.cu.o
.PHONY : cudfOperations/cudfComputeOps.cu.o

cudfOperations/cudfComputeOps.i: cudfOperations/cudfComputeOps.cu.i

.PHONY : cudfOperations/cudfComputeOps.i

# target to preprocess a source file
cudfOperations/cudfComputeOps.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/cudfOperations/cudfComputeOps.cu.i
.PHONY : cudfOperations/cudfComputeOps.cu.i

cudfOperations/cudfComputeOps.s: cudfOperations/cudfComputeOps.cu.s

.PHONY : cudfOperations/cudfComputeOps.s

# target to generate assembly for a file
cudfOperations/cudfComputeOps.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/cudfOperations/cudfComputeOps.cu.s
.PHONY : cudfOperations/cudfComputeOps.cu.s

main.o: main.cu.o

.PHONY : main.o

# target to build an object file
main.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library_execution.dir/build.make CMakeFiles/cross_library_execution.dir/main.cu.o
.PHONY : main.cu.o

main.i: main.cu.i

.PHONY : main.i

# target to preprocess a source file
main.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library_execution.dir/build.make CMakeFiles/cross_library_execution.dir/main.cu.i
.PHONY : main.cu.i

main.s: main.cu.s

.PHONY : main.s

# target to generate assembly for a file
main.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library_execution.dir/build.make CMakeFiles/cross_library_execution.dir/main.cu.s
.PHONY : main.cu.s

oneapiOperations/oneapiComputeOps.o: oneapiOperations/oneapiComputeOps.cpp.o

.PHONY : oneapiOperations/oneapiComputeOps.o

# target to build an object file
oneapiOperations/oneapiComputeOps.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/oneapiOperations/oneapiComputeOps.cpp.o
.PHONY : oneapiOperations/oneapiComputeOps.cpp.o

oneapiOperations/oneapiComputeOps.i: oneapiOperations/oneapiComputeOps.cpp.i

.PHONY : oneapiOperations/oneapiComputeOps.i

# target to preprocess a source file
oneapiOperations/oneapiComputeOps.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/oneapiOperations/oneapiComputeOps.cpp.i
.PHONY : oneapiOperations/oneapiComputeOps.cpp.i

oneapiOperations/oneapiComputeOps.s: oneapiOperations/oneapiComputeOps.cpp.s

.PHONY : oneapiOperations/oneapiComputeOps.s

# target to generate assembly for a file
oneapiOperations/oneapiComputeOps.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/oneapiOperations/oneapiComputeOps.cpp.s
.PHONY : oneapiOperations/oneapiComputeOps.cpp.s

test_tpch_queries/executeQueries.o: test_tpch_queries/executeQueries.cpp.o

.PHONY : test_tpch_queries/executeQueries.o

# target to build an object file
test_tpch_queries/executeQueries.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/test_tpch_queries/executeQueries.cpp.o
.PHONY : test_tpch_queries/executeQueries.cpp.o

test_tpch_queries/executeQueries.i: test_tpch_queries/executeQueries.cpp.i

.PHONY : test_tpch_queries/executeQueries.i

# target to preprocess a source file
test_tpch_queries/executeQueries.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/test_tpch_queries/executeQueries.cpp.i
.PHONY : test_tpch_queries/executeQueries.cpp.i

test_tpch_queries/executeQueries.s: test_tpch_queries/executeQueries.cpp.s

.PHONY : test_tpch_queries/executeQueries.s

# target to generate assembly for a file
test_tpch_queries/executeQueries.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_library.dir/build.make CMakeFiles/cross_library.dir/test_tpch_queries/executeQueries.cpp.s
.PHONY : test_tpch_queries/executeQueries.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cross_library"
	@echo "... cross_library_execution"
	@echo "... ArrayFireOperations/ArrayFireAdapter.o"
	@echo "... ArrayFireOperations/ArrayFireAdapter.i"
	@echo "... ArrayFireOperations/ArrayFireAdapter.s"
	@echo "... ArrayFireOperations/afComputeOps.o"
	@echo "... ArrayFireOperations/afComputeOps.i"
	@echo "... ArrayFireOperations/afComputeOps.s"
	@echo "... Base/BaseCompute.o"
	@echo "... Base/BaseCompute.i"
	@echo "... Base/BaseCompute.s"
	@echo "... BoostOperations/BoostAdapter.o"
	@echo "... BoostOperations/BoostAdapter.i"
	@echo "... BoostOperations/BoostAdapter.s"
	@echo "... BoostOperations/BoostComputeOps.o"
	@echo "... BoostOperations/BoostComputeOps.i"
	@echo "... BoostOperations/BoostComputeOps.s"
	@echo "... ThrustOperations/ThrustAdapter.o"
	@echo "... ThrustOperations/ThrustAdapter.i"
	@echo "... ThrustOperations/ThrustAdapter.s"
	@echo "... ThrustOperations/ThrustComputeOps.o"
	@echo "... ThrustOperations/ThrustComputeOps.i"
	@echo "... ThrustOperations/ThrustComputeOps.s"
	@echo "... cudfOperations/cudfComputeOps.o"
	@echo "... cudfOperations/cudfComputeOps.i"
	@echo "... cudfOperations/cudfComputeOps.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... oneapiOperations/oneapiComputeOps.o"
	@echo "... oneapiOperations/oneapiComputeOps.i"
	@echo "... oneapiOperations/oneapiComputeOps.s"
	@echo "... test_tpch_queries/executeQueries.o"
	@echo "... test_tpch_queries/executeQueries.i"
	@echo "... test_tpch_queries/executeQueries.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

